FROM ruby:3.3

WORKDIR /rails

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
  build-essential \
  git \
  libpq-dev \
  postgresql-client \
  nodejs \
  npm \
  && rm -rf /var/lib/apt/lists/*

RUN npm install -g yarn

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY package.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["bash", "-lc", "bundle exec rails db:prepare && bin/dev"]
